### ISSUE TITLE
Form for user registration 

### ISSUE THREAD

**Issue by krutarth4** [krutarth4/SHYFTX#10]
Provide information about what we want to ask for a new registered user from both stakeholder (Farmer and truckers)

**Comment by krutarth4** [comment]
@vahidjb Hey soon we will need the form, of what is supposed to be asked while registering farmer on the platform.

**Comment by vahidjb** [comment]
@krutarth4 

For Farmers/Brokers (Senders)
1. Registration Information

Business Information:
- Business Name
- Contact Person Name
- Address (including region and postal code)
- Contact Phone Number
- Email Address
- Type of Produce (e.g., fruits, vegetables, grains)
- Average Shipment Volume
- Preferred Shipping Frequency

................................................
Profile Setup:
Produce Types

- Shipping Preferences (e.g., preferred booking times, special handling needs) - need for marketing and communication later
- Payment Preferences (e.g., online, cash on delivery) - Good to have not must

Verification Documents:
- Business License
- Tax Identification Number (TIN)
- Any relevant agricultural certifications (e.g., organic certification) - Nice to Have

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For Riders (Truck Owners)
1. Registration and KYC Information

Personal Identification:
- Full Name
- Date of Birth
- Address
- Contact Phone Number
- Email Address
- Government-issued ID (ID card and, driver’s license)


Vehicle Information:

- Vehicle Type ****** I provided a list of types. it should be like the rider can choose one of them
- Vehicle Registration Number
- Vehicle Capacity
- Insurance Details
- Vehicle Inspection Certificate
- Driver Qualification Card (if applicable)

******* Vehicle Type*********
Standard Cargo Truck
Refrigerated Truck
Flatbed Truck
Box Truck
Grain Hopper Trucks
Tanker Trucks

Payment Information:

- Bank Account Details for Payments
- Pricing Per Kilometer

Verification Documents:

- Vehicle Registration Documents
- Proof of Insurance
- Recent Utility Bill or other Proof of Address
