### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by krutarth4** [krutarth4/SHYFTX#13]
Home page will first contain the details about the company and what we offer as a company 

Then we can have login and further information

**Comment by krutarth4** [comment]
@vahidjb might be a good idea to do the theming for the home page. 

TODO: 

- [ ] what kind of information we want to show the stakeholders 
- [ ] how to present our company image 
- [ ] Provide graphics if necessary alongside with the text

**Comment by vahidjb** [comment]
https://www.figma.com/design/t0O8noOL0OcdphMl4avOJi/Website-Wireframes-UI-Kit-(Community)?node-id=0-1&t=3ucJG3RvdxFVeQC5-1

**Comment by vahidjb** [comment]
Check content with Navy and Tom.
