### ISSUE TITLE
Data for Truckers

### ISSUE THREAD

**Issue by krutarth4** [krutarth4/SHYFTX#18]
Create a dummy data as json to create some profiles for the truckers

**Comment by krutarth4** [comment]
Need : 

- UID
- Name
- Lastname
- Nationality
- Bank account
- Truck details 
-

**Comment by vahidjb** [comment]
For Riders (Truck Owners)

Registration and KYC Information
Personal Identification:

Full Name
Date of Birth
Address
Contact Phone Number
Email Address
Government-issued ID (ID card and, driver’s license)
Vehicle Information:

Vehicle Type ****** I provided a list of types. it should be like the rider can choose one of them
Vehicle Registration Number
Vehicle Capacity
Insurance Details
Vehicle Inspection Certificate
Driver Qualification Card (if applicable)
******* Vehicle Type*********
Standard Cargo Truck
Refrigerated Truck
Flatbed Truck
Box Truck
Grain Hopper Trucks
Tanker Trucks

Payment Information:

Bank Account Details for Payments
Pricing Per Kilometer
Verification Documents:

Vehicle Registration Documents
Proof of Insurance
Recent Utility Bill or other Proof of Address

**Comment by krutarth4** [comment]
@vahidjb nice thanks !
