### ISSUE TITLE
Logo SHYFTX

### ISSUE THREAD

**Issue by krutarth4** [krutarth4/SHYFTX#8]

**Comment by krutarth4** [comment]
@vahidjb upload a jpeg or png image

**Comment by vahidjb** [comment]
Added as .rar to google drive

**Comment by krutarth4** [comment]
@vahidjb is it not possible to have it as a jpeg, I think it would be easier to add it directly to the home page and I think you can directly upload it in git iteself.

@KindTechs maybe you can provide your input on it as it is on home page , however you find it better and easier

**Comment by krutarth4** [comment]
![Image](https://github.com/krutarth4/SHYFTX/assets/74930393/71487b80-a85e-44d7-8fe1-5de368279a16)

**Comment by krutarth4** [comment]
Here is the Png image for the logo

**Comment by vahidjb** [comment]
![Logo-Type](https://github.com/krutarth4/SHYFTX/assets/76093425/c83b5279-605d-42cd-8a46-6e6184e6c24e)

Actually, this is our logo with a blue color (you can find the main colors on Figma) and use purple for the secondary and background color, as well as for the header.
